# Generated by Django 4.0.6 on 2022-08-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footerLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام دسته لینک')),
            ],
            options={
                'verbose_name': 'دسته بندی آدرس ها در فوتر',
                'verbose_name_plural': 'دسته بندی های آدرس ها در فوتر',
            },
        ),
        migrations.CreateModel(
            name='settingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('siteEnglishName', models.CharField(max_length=200, verbose_name='نام انگلیسی سایت')),
                ('siteUrl', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('siteAddress', models.CharField(max_length=200, verbose_name='آدرس سایت')),
                ('sitePhone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن سایت')),
                ('siteFax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس سایت')),
                ('siteEmail', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل سایت')),
                ('siteCopyRight', models.CharField(max_length=200, verbose_name='متن کپی رایت سایت')),
                ('siteLogo', models.ImageField(upload_to='uploads/images/siteSettings', verbose_name='لوگو سایت')),
                ('siteMap', models.ImageField(upload_to='uploads/images/siteSettings', verbose_name='نقشه سایت')),
                ('siteAboutUs', models.TextField(verbose_name='درباره ما')),
                ('isMainSettings', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنطیمات',
            },
        ),
        migrations.CreateModel(
            name='footerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('titleEnglish', models.CharField(max_length=200, verbose_name='نمایش متن کمکی')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('footerLinkRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteSettingsApp.footerlinkbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'آدرس در فوتر',
                'verbose_name_plural': 'آدرس ها در فوتر',
            },
        ),
    ]
