# Generated by Django 4.0.6 on 2022-08-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinkbox',
            name='titleEnglish',
            field=models.CharField(max_length=200, null=True, verbose_name='نام انگلیسی دسته لینک'),
        ),
    ]
