# Generated by Django 4.0.6 on 2022-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettingsApp', '0002_footerlinkbox_titleenglish'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmodel',
            name='siteRights',
            field=models.TextField(blank=True, null=True, verbose_name='متن کپی رایت سایت'),
        ),
    ]
