# Generated by Django 4.0.6 on 2022-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettingsApp', '0003_settingmodel_siterights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('titleEN', models.CharField(max_length=200, verbose_name='عنوان انگلیسی')),
                ('url', models.CharField(max_length=200, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('description', models.TextField(verbose_name='توضیحات اسلایدر')),
                ('image', models.ImageField(upload_to='images/sliders/', verbose_name='تصویر اسلایدر')),
                ('isActive', models.BooleanField(verbose_name='فعال بودن /نبودن')),
            ],
            options={
                'verbose_name': ' اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
