# Generated by Django 4.0.6 on 2022-08-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettingsApp', '0005_alter_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='footerLinkRelation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footerLinkRelation', to='siteSettingsApp.footerlinkbox', verbose_name='دسته بندی'),
        ),
    ]
