# Generated by Django 4.0.6 on 2022-09-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettingsApp', '0006_alter_footerlink_footerlinkrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان منو')),
                ('url', models.URLField(max_length=100, verbose_name='آدرس url')),
                ('url_v1', models.URLField(max_length=100, verbose_name='آدرس url برای ورژن1')),
            ],
            options={
                'verbose_name': 'آیتم منوی کاربر',
                'verbose_name_plural': 'آیتم های منوی کاربران',
            },
        ),
    ]
