# Generated by Django 4.0.6 on 2022-08-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('numbers', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('dateOfCreate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('shortDescription', models.CharField(db_index=True, default='empty', max_length=360, verbose_name='توضیحات کوتاه')),
                ('Description', models.TextField(db_index=True, verbose_name='توضیحات اصلی')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('isDelete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام برند')),
                ('titleEN', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام انگلیسی برند')),
                ('isActive', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='ProductsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='تگ محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='productionsApp.products')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان دسته بندی')),
                ('urlTitle', models.CharField(db_index=True, max_length=300, verbose_name='Url عنوان در')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/category', verbose_name='تصویر دسته بندی')),
                ('isActive', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('isDelete', models.BooleanField(null=True, verbose_name='حذف شده / نشده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productionsApp.products', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی  های محصولات',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productionsApp.productsbrand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(related_name='productCategories', to='productionsApp.productscategory', verbose_name='دسته بندی محصول'),
        ),
    ]
