# Generated by Django 4.0.6 on 2022-08-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام')),
                ('titleEN', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام انگلیسی')),
                ('isActive', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته بندی والد',
                'verbose_name_plural': 'دسته بندی های والد',
            },
        ),
    ]
