# Generated by Django 4.0.6 on 2022-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0004_productsbrand_description_productsbrand_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsbrand',
            name='shortDescription',
            field=models.TextField(null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
