# Generated by Django 4.0.6 on 2022-08-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0005_productsbrand_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsbrand',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ نوشته'),
        ),
    ]
