# Generated by Django 4.0.6 on 2022-08-09 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productionsApp', '0007_productscomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscomments',
            options={'verbose_name': 'نظر درباره محصول', 'verbose_name_plural': 'نظرات محصولات'},
        ),
        migrations.CreateModel(
            name='BrandsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر')),
                ('message', models.TextField(verbose_name='متن نظر')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionsApp.productsbrand', verbose_name='نام برند')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productionsApp.brandscomments', verbose_name='والد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'نظر درباره برند',
                'verbose_name_plural': 'نظرات برند',
            },
        ),
    ]
