# Generated by Django 4.0.6 on 2022-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0008_alter_productscomments_options_brandscomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandscomments',
            name='isActive',
            field=models.BooleanField(null=True, verbose_name='نمایش نظر'),
        ),
        migrations.AddField(
            model_name='productsbrand',
            name='haveComments',
            field=models.BooleanField(blank=True, null=True, verbose_name='نمایش نظرات'),
        ),
    ]
