# Generated by Django 4.0.6 on 2022-08-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0009_brandscomments_isactive_productsbrand_havecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='haveComments',
            field=models.BooleanField(blank=True, null=True, verbose_name='نمایش نظرات'),
        ),
    ]
