# Generated by Django 4.0.6 on 2022-08-14 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productionsApp', '0011_productsvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='امتیاز')),
                ('isRating', models.BooleanField(verbose_name='نظر داده / نداده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionsApp.products', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز محصول',
                'verbose_name_plural': 'امتبازات محصولات',
            },
        ),
    ]
