# Generated by Django 4.0.6 on 2022-08-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0012_productsrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsrating',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='امتیاز'),
        ),
    ]
