# Generated by Django 4.0.6 on 2022-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0014_alter_products_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='numbers',
        ),
        migrations.AddField(
            model_name='products',
            name='productCount',
            field=models.IntegerField(default=1, verbose_name='تعداد محصول'),
        ),
    ]
