# Generated by Django 4.0.6 on 2022-08-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0015_remove_products_numbers_products_productcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productCount',
            field=models.IntegerField(default=0, verbose_name='تعداد محصول'),
        ),
    ]
