# Generated by Django 4.1 on 2022-08-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productionsApp', '0017_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsvisit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsvisit', to='productionsApp.products', verbose_name='محصول'),
        ),
    ]
