# Generated by Django 4.0.6 on 2022-08-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('email', models.CharField(max_length=300, verbose_name='آدرس ایمیل')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان پیام')),
                ('message', models.TextField(verbose_name='متن پیام تماس با ما')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(blank=True, null=True, verbose_name='متن پاسخ تماس با ما')),
                ('isReadByAdmin', models.BooleanField(default=False, verbose_name='خوانده شده توسط مدیر')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
