# Generated by Django 4.0.6 on 2022-08-29 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usercontact', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
