# Generated by Django 4.0.6 on 2022-08-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
