# Generated by Django 4.1 on 2022-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccountApp', '0002_user_aboutuser_user_address_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن همراه'),
        ),
    ]
